kind: "ReplicationController"
apiVersion: "v1"
metadata:
  name: "datanode"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: "datanode"
    spec:
      containers:
        -
          name: "datanode"
          image: "bde2020/hadoop-datanode:1.0.0-hadoop2.7.1"
          env:
            -
              name: "HIVE_SITE_CONF_javax_jdo_option_ConnectionURL"
              value: "jdbc:postgresql://hive-metastore-postgresql/metastore"
            -
              name: "HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName"
              value: "org.postgresql.Driver"
            -
              name: "HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName"
              value: "hive"
            -
              name: "HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword"
              value: "hive"
            -
              name: "HIVE_SITE_CONF_datanucleus_autoCreateSchema"
              value: "false"
            -
              name: "HIVE_SITE_CONF_hive_metastore_uris"
              value: "thrift://hive-metastore:9083"
            -
              name: "CORE_CONF_fs_defaultFS"
              value: "hdfs://namenode:8020"
            -
              name: "CORE_CONF_hadoop_http_staticuser_user"
              value: "root"
            -
              name: "CORE_CONF_hadoop_proxyuser_hue_hosts"
              value: "*"
            -
              name: "CORE_CONF_hadoop_proxyuser_hue_groups"
              value: "*"
            -
              name: "HDFS_CONF_dfs_webhdfs_enabled"
              value: "true"
            -
              name: "HDFS_CONF_dfs_permissions_enabled"
              value: "false"
            -
              name: "YARN_CONF_yarn_log___aggregation___enable"
              value: "true"
            -
              name: "YARN_CONF_yarn_resourcemanager_recovery_enabled"
              value: "true"
            -
              name: "YARN_CONF_yarn_resourcemanager_store_class"
              value: "org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore"
            -
              name: "YARN_CONF_yarn_resourcemanager_fs_state___store_uri"
              value: "/rmstate"
            -
              name: "YARN_CONF_yarn_nodemanager_remote___app___log___dir"
              value: "/app-logs"
            -
              name: "YARN_CONF_yarn_log_server_url"
              value: "http://historyserver:8188/applicationhistory/logs/"
            -
              name: "YARN_CONF_yarn_timeline___service_enabled"
              value: "true"
            -
              name: "YARN_CONF_yarn_timeline___service_generic___application___history_enabled"
              value: "true"
            -
              name: "YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled"
              value: "true"
            -
              name: "YARN_CONF_yarn_resourcemanager_hostname"
              value: "resourcemanager"
            -
              name: "YARN_CONF_yarn_timeline___service_hostname"
              value: "historyserver"
            -
              name: "YARN_CONF_yarn_resourcemanager_address"
              value: "resourcemanager:8032"
            -
              name: "YARN_CONF_yarn_resourcemanager_scheduler_address"
              value: "resourcemanager:8030"
            -
              name: "YARN_CONF_yarn_resourcemanager_resource__tracker_address"
              value: "resourcemanager:8031"
          volumeMounts:
            -
              name: "datanode-data"
              mountPath: "/hadoop/dfs/data"
      volumes:
        -
          name: "datanode-data"
          hostPath:
            path: "/media/falkonry/hadoop-datanode"
      restartPolicy: "Always"

